import { Montserrat } from 'next/font/google'
import type { Metadata } from 'next'
import './globals.css'
import { Nav } from '@/components'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-sw-global-bg`}>
        <header className="mb-3 h-16 shadow-lg">
          <Nav
            links={[
              { text: 'home', href: '/' },
              { text: 'films', href: '/films' },
            ]}
          />
        </header>
        <main className="flex flex-col items-center justify-center py-12">
          {children}
        </main>
      </body>
    </html>
  )
}
